# Generated by Django 4.2.2 on 2023-07-09 03:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mcq", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="question",
            table="Questions",
        ),
    ]
