# Generated by Django 4.2.2 on 2023-07-09 03:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mcq", "0002_alter_question_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="choice",
            table="Choice",
        ),
        migrations.AlterModelTable(
            name="question",
            table="Question",
        ),
    ]
